sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: gyrs

  redis:
    host: localhost
    port: 6379
    password: gyrs
    database: 10
  wechat:
    appid: wx68177f1788f52a44
    secret: 602794c04908fd679916ca1a8e2fceb3


